remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
title: "                                                                                        
@@@**@@**@@@@@@                      *@@@@*  *@@@@**           *@@@                    mm@***@m@
@*   @@   *@ @@                        @@      @@                @@                  m@@*     *@
     @@      @@@@@@@m    mm@*@@        @@      @@     m@@*@@m    @@  *@@*   *@@*     @@*       *
     !@      @@    @@   m@*   @@       @@@@@@@@@@    @@*   *@@   !@    @@   m@       @@         
     !@      @@    @!   !@******       !@      @!    @@     @@   !@     @@ m!        @!m        
     !@      @!    @!   !@m    m       !@      @!    @@     !@   !@      @@!         *!@m     m*
     !@      !!    !!   !!******       :!      !!    !@     !!   !!      @!!         !!!        
    " i@     !:    !:   :!!            :!      :!    !!!   !!!   :!      !!:         :!!:     !*
  : :!::   : :   : : :  : : ::      ::: :   : :!::   : : : :  : : :     !!            : : : :! 
                                                                       ::!                      
                                                                     :                        "

description: A personal blog
author: tg
